language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - iojs
script: "npm run-script test-cover"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
sudo: false
